import { useEffect, useMemo, useRef, useState } from 'react'

const WORDS = 'time place word light quiet room memory return change arrive evening street thought motion write type rhythm paper sound window small under over after before people world begin simple clear focus keyboard story every another still around between without inside outside open close slow quick soft space'.split(' ')
function makeText(count,punctuation,numbers){const words=Array.from({length:count},()=>WORDS[Math.floor(Math.random()*WORDS.length)]);if(punctuation){for(let i=7;i<words.length;i+=8)words[i]+=i%16===7?',':'.';words[0]=words[0][0].toUpperCase()+words[0].slice(1)}if(numbers&&words.length>5)words[Math.min(5,words.length-1)]+=` ${Math.floor(Math.random()*90+10)}`;return words.join(' ')}

export default function Type(){
 const[mode,setMode]=useState('time'),[amount,setAmount]=useState(30),[punctuation,setPunctuation]=useState(false),[numbers,setNumbers]=useState(false),[seed,setSeed]=useState(0),[input,setInput]=useState(''),[startedAt,setStartedAt]=useState(null),[elapsed,setElapsed]=useState(0),[finished,setFinished]=useState(false)
 const inputRef=useRef(null),textRef=useRef(null),caretRef=useRef(null),wrapRef=useRef(null)
 const text=useMemo(()=>makeText(mode==='words'?amount:120,punctuation,numbers),[mode,amount,punctuation,numbers,seed])
 const restart=()=>{setInput('');setStartedAt(null);setElapsed(0);setFinished(false);setSeed(v=>v+1);if(textRef.current)textRef.current.style.setProperty('--test-offset','0px');requestAnimationFrame(()=>inputRef.current?.focus({preventScroll:true}))}
 const choose=(m,n)=>{setMode(m);setAmount(n);setTimeout(restart,0)}
 useEffect(()=>inputRef.current?.focus({preventScroll:true}),[])
 useEffect(()=>{if(!startedAt||finished)return;const tick=()=>{const s=(Date.now()-startedAt)/1000;setElapsed(s);if(mode==='time'&&s>=amount)setFinished(true)};tick();const timer=setInterval(tick,50);return()=>clearInterval(timer)},[startedAt,finished,mode,amount])
 useEffect(()=>{const active=textRef.current?.querySelector(`[data-index="${Math.min(input.length,text.length-1)}"]`);if(!active||!caretRef.current||!textRef.current||!wrapRef.current)return;const a=active.getBoundingClientRect(),p=textRef.current.getBoundingClientRect();caretRef.current.style.transform=`translate3d(${a.left-p.left}px,${a.top-p.top}px,0)`;caretRef.current.style.height=`${a.height}px`;const lineHeight=parseFloat(getComputedStyle(textRef.current).lineHeight)||70;const rawTop=active.offsetTop;const line=Math.round(rawTop/lineHeight);const offset=line>1?-(line-1)*lineHeight:0;textRef.current.style.setProperty('--test-offset',`${offset}px`)},[input,text])
 useEffect(()=>{const onKey=e=>{if(e.key==='Tab'){e.preventDefault();restart()}if(e.key==='Escape')inputRef.current?.blur()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)})
 const handleInput=e=>{if(finished)return;const value=e.target.value.slice(0,text.length);if(!startedAt&&value.length)setStartedAt(Date.now());setInput(value);if(mode==='words'&&value.length>=text.length)setFinished(true)}
 const correct=[...input].filter((c,i)=>c===text[i]).length,incorrect=input.length-correct,minutes=Math.max(elapsed/60,1/600),wpm=Math.max(0,Math.round(correct/5/minutes)),raw=Math.max(0,Math.round(input.length/5/minutes)),accuracy=input.length?Math.round(correct/input.length*1000)/10:100,remaining=mode==='time'?Math.max(0,Math.ceil(amount-elapsed)):Math.max(0,amount-input.trim().split(/\s+/).filter(Boolean).length)
 return <main className={`type ${startedAt&&!finished?'isTyping':''}`} onClick={()=>inputRef.current?.focus({preventScroll:true})}>
 {!finished&&<><div className="typebar"><button className={mode==='time'?'active':''} onClick={e=>{e.stopPropagation();choose('time',mode==='time'?amount:30)}}>TIME</button>{[15,30,60,120].map(n=><button key={n} className={mode==='time'&&amount===n?'active':''} onClick={e=>{e.stopPropagation();choose('time',n)}}>{n}</button>)}<i/><button className={mode==='words'?'active':''} onClick={e=>{e.stopPropagation();choose('words',mode==='words'?amount:25)}}>WORDS</button>{[10,25,50,100].map(n=><button key={n} className={mode==='words'&&amount===n?'active':''} onClick={e=>{e.stopPropagation();choose('words',n)}}>{n}</button>)}<i/><button className={punctuation?'active':''} onClick={e=>{e.stopPropagation();setPunctuation(v=>!v);restart()}}>PUNCTUATION</button><button className={numbers?'active':''} onClick={e=>{e.stopPropagation();setNumbers(v=>!v);restart()}}>NUMBERS</button></div><div className="testWrap" ref={wrapRef}><div className="test" ref={textRef}><span className="smoothCaret" ref={caretRef}/>{[...text].map((c,i)=><span data-index={i} key={`${seed}-${i}`} className={i<input.length?(input[i]===c?'ok':'bad'):''}>{c}</span>)}</div><input className="ghostInput" ref={inputRef} value={input} onChange={handleInput} autoComplete="off" autoCapitalize="off" spellCheck="false"/></div><div className="meta"><span>{startedAt?`${wpm} WPM · ${accuracy}%`:'START TYPING'}</span><span>{remaining} {mode==='time'?'SEC':'WORDS'} · TAB RESTART</span></div></>}
 {finished&&<div className="result"><p>SESSION / {mode.toUpperCase()} {amount}</p><strong>{wpm}</strong><h3>WORDS / MINUTE</h3><div className="resultGrid"><span><b>{accuracy}%</b>ACCURACY</span><span><b>{raw}</b>RAW</span><span><b>{incorrect}</b>ERRORS</span><span><b>{Math.round(elapsed)}s</b>TIME</span></div><button onClick={restart}>AGAIN ↗</button></div>}
 </main>
}
