import { useEffect, useMemo, useRef, useState } from 'react'
import { useSettings } from '../settings'

const pools={normal:'time place word light quiet room memory return change arrive evening street thought motion write type rhythm paper sound window small under over after before people world begin simple clear focus keyboard story every another still around between without inside outside open close slow quick soft space',expert:'absolute boundary category delicate emerge fragment gravity hesitate illuminate junction language measure narrow observe parallel question rhythm sequence theory unusual variable whisper abstract consequence',master:'acknowledgment bureaucracy circumference disproportionate entrepreneurial fluorescent hierarchy inconspicuous juxtaposition knowledgeable miscellaneous notwithstanding pronunciation questionnaire responsibility synchronization unprecedented vulnerability'}
const makeText=(count,punctuation,numbers,difficulty)=>{const pool=pools[difficulty].split(' '),words=Array.from({length:count},()=>pool[Math.floor(Math.random()*pool.length)]);if(punctuation){for(let i=6;i<words.length;i+=7)words[i]+=i%14===6?',':'.';words[0]=words[0][0].toUpperCase()+words[0].slice(1)}if(numbers)for(let i=5;i<words.length;i+=17)words[i]+=` ${Math.floor(Math.random()*900+100)}`;return words.join(' ')}
const sound=(settings,error=false)=>{if(!settings.sound.enabled||(error&&!settings.sound.error))return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();const base=settings.sound.profile==='mechanical'?180:settings.sound.profile==='typewriter'?120:settings.sound.profile==='minimal'?360:260;o.frequency.value=error?110:base+Math.random()*35;g.gain.value=settings.sound.volume*.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.025);o.onended=()=>c.close()}catch{}}

export default function Type(){
 const {settings,openSettings}=useSettings(),cfg=settings.test
 const[seed,setSeed]=useState(0),[input,setInput]=useState(''),[startedAt,setStartedAt]=useState(null),[elapsed,setElapsed]=useState(0),[finished,setFinished]=useState(false)
 const inputRef=useRef(null),textRef=useRef(null),caretRef=useRef(null)
 const amount=cfg.mode==='time'?cfg.time:cfg.words,text=useMemo(()=>makeText(cfg.mode==='words'?cfg.words:180,cfg.punctuation,cfg.numbers,cfg.difficulty),[cfg.mode,cfg.words,cfg.punctuation,cfg.numbers,cfg.difficulty,seed])
 const restart=()=>{setInput('');setStartedAt(null);setElapsed(0);setFinished(false);setSeed(v=>v+1);textRef.current?.style.setProperty('--test-offset','0px');requestAnimationFrame(()=>inputRef.current?.focus({preventScroll:true}))}
 useEffect(()=>restart(),[cfg.mode,cfg.time,cfg.words,cfg.punctuation,cfg.numbers,cfg.difficulty])
 useEffect(()=>{document.body.classList.toggle('typingActive',!!startedAt&&!finished);return()=>document.body.classList.remove('typingActive')},[startedAt,finished])
 useEffect(()=>{if(!startedAt||finished)return;const tick=()=>{const s=(Date.now()-startedAt)/1000;setElapsed(s);if(cfg.mode==='time'&&s>=cfg.time)setFinished(true)};tick();const t=setInterval(tick,50);return()=>clearInterval(t)},[startedAt,finished,cfg.mode,cfg.time])
 useEffect(()=>{const active=textRef.current?.querySelector(`[data-index="${Math.min(input.length,text.length-1)}"]`);if(!active||!caretRef.current||!textRef.current)return;const a=active.getBoundingClientRect(),p=textRef.current.getBoundingClientRect();caretRef.current.style.transform=`translate3d(${a.left-p.left}px,${a.top-p.top}px,0)`;caretRef.current.style.height=`${a.height}px`;const lh=parseFloat(getComputedStyle(textRef.current).lineHeight)||60,line=Math.round(active.offsetTop/lh),offset=line>1?-(line-1)*lh:0;textRef.current.style.setProperty('--test-offset',`${offset}px`)},[input,text,settings.typography,settings.appearance.lines])
 useEffect(()=>{const key=e=>{if(e.key==='Tab'){e.preventDefault();restart()}if(e.key==='Escape')inputRef.current?.blur();if(settings.behavior.confidence&&e.key==='Backspace')e.preventDefault()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[settings.behavior.confidence])
 const handleInput=e=>{if(finished)return;let value=e.target.value.slice(0,text.length);const old=input;if(value.length>old.length){const idx=value.length-1,bad=value[idx]!==text[idx];if(bad&&settings.behavior.stopOnError==='letter'){value=old;sound(settings,true)}else sound(settings,bad)}if(settings.behavior.strictSpace&&value.length>old.length&&value.at(-1)===' '&&text[value.length-1]!==' ')return;if(!startedAt&&value.length)setStartedAt(Date.now());setInput(value);if(cfg.mode==='words'&&value.length>=text.length)setFinished(true)}
 const correct=[...input].filter((c,i)=>c===text[i]).length,incorrect=input.length-correct,min=Math.max(elapsed/60,1/600),wpm=Math.max(0,Math.round(correct/5/min)),raw=Math.max(0,Math.round(input.length/5/min)),accuracy=input.length?Math.round(correct/input.length*1000)/10:100,remaining=cfg.mode==='time'?Math.max(0,Math.ceil(cfg.time-elapsed)):Math.max(0,cfg.words-input.trim().split(/\s+/).filter(Boolean).length)
 const speed={off:'0ms',slow:'180ms',medium:'90ms',fast:'45ms'}[settings.caret.speed],fontClass=`font-${settings.typography.font}`
 return <main className={`typePage controls-${settings.appearance.controls} typed-${settings.behavior.typedText}`} onClick={()=>inputRef.current?.focus({preventScroll:true})}>
  {!finished?<>
   <div className="typeContext"><button onClick={e=>{e.stopPropagation();openSettings('test')}}>01 / TYPE</button><button onClick={e=>{e.stopPropagation();openSettings('test')}}>{cfg.mode.toUpperCase()} / {amount}</button><button onClick={e=>{e.stopPropagation();openSettings('test')}}>{cfg.language.toUpperCase()}</button><button onClick={e=>{e.stopPropagation();openSettings('test')}}>{cfg.difficulty.toUpperCase()}</button></div>
   {settings.appearance.timer==='bar'&&cfg.mode==='time'&&<div className="timerBar"><i style={{width:`${Math.min(100,elapsed/cfg.time*100)}%`}}/></div>}
   <div className="typeViewport" style={{'--lines':settings.appearance.lines}}><div className={`typingText ${fontClass} scroll-${settings.behavior.lineScroll}`} ref={textRef} style={{'--caret-speed':speed,'--caret-width':`${settings.caret.width}px`}}><span className={`smoothCaret caret-${settings.caret.style} ${settings.caret.blink?'blink':''}`} ref={caretRef}/>{[...text].map((c,i)=><span data-index={i} key={`${seed}-${i}`} className={i<input.length?(input[i]===c?'ok':'bad'):''}>{c}</span>)}</div><input className="ghostInput" ref={inputRef} value={input} onChange={handleInput} autoComplete="off" autoCapitalize="off" spellCheck="false"/></div>
   <div className="typeStatus"><span>{startedAt&&settings.appearance.liveWpm?`${wpm} WPM`:startedAt?'TYPING':'BEGIN'}</span>{startedAt&&settings.appearance.liveAccuracy&&<span>{accuracy}%</span>}{settings.appearance.timer!=='hidden'&&<span>{remaining} {cfg.mode==='time'?'SEC':'WORDS'}</span>}<span>TAB / RESTART</span></div>
  </>:<div className="result"><p>SESSION / {cfg.mode.toUpperCase()} {amount}</p><strong>{wpm}</strong><h3>WORDS / MINUTE</h3><div className="resultGrid"><span><b>{accuracy}%</b>ACCURACY</span><span><b>{raw}</b>RAW</span><span><b>{incorrect}</b>ERRORS</span><span><b>{Math.round(elapsed)}s</b>TIME</span></div><button onClick={restart}>AGAIN ↗</button></div>}
 </main>
}
